In [18]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

pd.set_option('display.max_colwidth', None)
df = pd.read_csv("../data/clickbait_title_classification.csv")
df.head()

,title,clickbait
0,""".asia"" domain applications near 300,000 on opening of registration",0
1,"""1 Indian + 1 Indian = Unrelatable"": Television's Race Equations",1
2,"""7th Heaven"" television series comes to an end",0
3,"""Arm Glow"" Is Your New Life Goal, Thanks To Lupita Nyong'o",1
4,"""Beans Memes"" Is The Only Twitter Account That Actually Matters",1

In [19]:
def clean_text(text: str):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text
print(clean_text("You Won't BELIEVE This!!"))

you wont believe this

In [20]:
df['clean_title'] = df['title'].apply(clean_text)
df.head()

,title,clickbait,clean_title
0,""".asia"" domain applications near 300,000 on opening of registration",0,asia domain applications near 300000 on opening of registration
1,"""1 Indian + 1 Indian = Unrelatable"": Television's Race Equations",1,1 indian 1 indian unrelatable televisions race equations
2,"""7th Heaven"" television series comes to an end",0,7th heaven television series comes to an end
3,"""Arm Glow"" Is Your New Life Goal, Thanks To Lupita Nyong'o",1,arm glow is your new life goal thanks to lupita nyongo
4,"""Beans Memes"" Is The Only Twitter Account That Actually Matters",1,beans memes is the only twitter account that actually matters

In [21]:
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['clean_title'])
Y = df['clickbait']
print(X.shape)
print(Y.shape)

(32000, 5000)
(32000,)

In [22]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

print(X_train.shape)
print(Y_train.shape)

(25600, 5000)
(25600,)